// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息ID
type MessageID int32

const (
	MessageID_MSG_Ping               MessageID = 0
	MessageID_MSG_Pong               MessageID = 1
	MessageID_MSG_Login_C2S          MessageID = 2
	MessageID_MSG_Login_S2C          MessageID = 3
	MessageID_MSG_Logout_C2S         MessageID = 4
	MessageID_MSG_Logout_S2C         MessageID = 5
	MessageID_MSG_JoinRoom_C2S       MessageID = 6
	MessageID_MSG_JoinRoom_S2C       MessageID = 7
	MessageID_MSG_EnterRoom_S2C      MessageID = 8
	MessageID_MSG_PlayerAction_C2S   MessageID = 9
	MessageID_MSG_PlayerAction_SC2   MessageID = 10
	MessageID_MSG_ActionResult_C2S   MessageID = 11
	MessageID_MSG_ActionResult_S2C   MessageID = 12
	MessageID_MSG_ProgressBar_C2S    MessageID = 13
	MessageID_MSG_ProgressBar_S2C    MessageID = 14
	MessageID_MSG_DownLuckyBag_S2C   MessageID = 15
	MessageID_MSG_ReCreatGold_S2C    MessageID = 16
	MessageID_MSG_GetRewards_S2C     MessageID = 17
	MessageID_MSG_PickUpGold_C2S     MessageID = 18
	MessageID_MSG_PickUpGold_S2C     MessageID = 19
	MessageID_MSG_ChangeRoomCfg_C2S  MessageID = 20
	MessageID_MSG_ChangeRoomCfg_S2C  MessageID = 21
	MessageID_MSG_SendCoordinate_C2S MessageID = 22
	MessageID_MSG_ErrorMsg_S2C       MessageID = 23
)

var MessageID_name = map[int32]string{
	0:  "MSG_Ping",
	1:  "MSG_Pong",
	2:  "MSG_Login_C2S",
	3:  "MSG_Login_S2C",
	4:  "MSG_Logout_C2S",
	5:  "MSG_Logout_S2C",
	6:  "MSG_JoinRoom_C2S",
	7:  "MSG_JoinRoom_S2C",
	8:  "MSG_EnterRoom_S2C",
	9:  "MSG_PlayerAction_C2S",
	10: "MSG_PlayerAction_SC2",
	11: "MSG_ActionResult_C2S",
	12: "MSG_ActionResult_S2C",
	13: "MSG_ProgressBar_C2S",
	14: "MSG_ProgressBar_S2C",
	15: "MSG_DownLuckyBag_S2C",
	16: "MSG_ReCreatGold_S2C",
	17: "MSG_GetRewards_S2C",
	18: "MSG_PickUpGold_C2S",
	19: "MSG_PickUpGold_S2C",
	20: "MSG_ChangeRoomCfg_C2S",
	21: "MSG_ChangeRoomCfg_S2C",
	22: "MSG_SendCoordinate_C2S",
	23: "MSG_ErrorMsg_S2C",
}

var MessageID_value = map[string]int32{
	"MSG_Ping":               0,
	"MSG_Pong":               1,
	"MSG_Login_C2S":          2,
	"MSG_Login_S2C":          3,
	"MSG_Logout_C2S":         4,
	"MSG_Logout_S2C":         5,
	"MSG_JoinRoom_C2S":       6,
	"MSG_JoinRoom_S2C":       7,
	"MSG_EnterRoom_S2C":      8,
	"MSG_PlayerAction_C2S":   9,
	"MSG_PlayerAction_SC2":   10,
	"MSG_ActionResult_C2S":   11,
	"MSG_ActionResult_S2C":   12,
	"MSG_ProgressBar_C2S":    13,
	"MSG_ProgressBar_S2C":    14,
	"MSG_DownLuckyBag_S2C":   15,
	"MSG_ReCreatGold_S2C":    16,
	"MSG_GetRewards_S2C":     17,
	"MSG_PickUpGold_C2S":     18,
	"MSG_PickUpGold_S2C":     19,
	"MSG_ChangeRoomCfg_C2S":  20,
	"MSG_ChangeRoomCfg_S2C":  21,
	"MSG_SendCoordinate_C2S": 22,
	"MSG_ErrorMsg_S2C":       23,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Account              float64  `protobuf:"fixed64,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *PlayerInfo) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type Login_C2S struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C2S) Reset()         { *m = Login_C2S{} }
func (m *Login_C2S) String() string { return proto.CompactTextString(m) }
func (*Login_C2S) ProtoMessage()    {}
func (*Login_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Login_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C2S.Unmarshal(m, b)
}
func (m *Login_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C2S.Marshal(b, m, deterministic)
}
func (m *Login_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C2S.Merge(m, src)
}
func (m *Login_C2S) XXX_Size() int {
	return xxx_messageInfo_Login_C2S.Size(m)
}
func (m *Login_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C2S proto.InternalMessageInfo

func (m *Login_C2S) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Login_C2S) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *Login_C2S) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Login_S2C struct {
	IsBack               bool        `protobuf:"varint,1,opt,name=IsBack,proto3" json:"IsBack,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,2,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Login_S2C) Reset()         { *m = Login_S2C{} }
func (m *Login_S2C) String() string { return proto.CompactTextString(m) }
func (*Login_S2C) ProtoMessage()    {}
func (*Login_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Login_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S2C.Unmarshal(m, b)
}
func (m *Login_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S2C.Marshal(b, m, deterministic)
}
func (m *Login_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S2C.Merge(m, src)
}
func (m *Login_S2C) XXX_Size() int {
	return xxx_messageInfo_Login_S2C.Size(m)
}
func (m *Login_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S2C proto.InternalMessageInfo

func (m *Login_S2C) GetIsBack() bool {
	if m != nil {
		return m.IsBack
	}
	return false
}

func (m *Login_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type Logout_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_C2S) Reset()         { *m = Logout_C2S{} }
func (m *Logout_C2S) String() string { return proto.CompactTextString(m) }
func (*Logout_C2S) ProtoMessage()    {}
func (*Logout_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *Logout_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_C2S.Unmarshal(m, b)
}
func (m *Logout_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_C2S.Marshal(b, m, deterministic)
}
func (m *Logout_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_C2S.Merge(m, src)
}
func (m *Logout_C2S) XXX_Size() int {
	return xxx_messageInfo_Logout_C2S.Size(m)
}
func (m *Logout_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_C2S proto.InternalMessageInfo

type Logout_S2C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_S2C) Reset()         { *m = Logout_S2C{} }
func (m *Logout_S2C) String() string { return proto.CompactTextString(m) }
func (*Logout_S2C) ProtoMessage()    {}
func (*Logout_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Logout_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_S2C.Unmarshal(m, b)
}
func (m *Logout_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_S2C.Marshal(b, m, deterministic)
}
func (m *Logout_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_S2C.Merge(m, src)
}
func (m *Logout_S2C) XXX_Size() int {
	return xxx_messageInfo_Logout_S2C.Size(m)
}
func (m *Logout_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_S2C proto.InternalMessageInfo

type RoomData struct {
	RoomId               string      `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	CfgId                string      `protobuf:"bytes,2,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,3,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	CoinList             []string    `protobuf:"bytes,4,rep,name=coinList,proto3" json:"coinList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomData) GetCfgId() string {
	if m != nil {
		return m.CfgId
	}
	return ""
}

func (m *RoomData) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *RoomData) GetCoinList() []string {
	if m != nil {
		return m.CoinList
	}
	return nil
}

type JoinRoom_C2S struct {
	Cfg                  string   `protobuf:"bytes,1,opt,name=cfg,proto3" json:"cfg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom_C2S) Reset()         { *m = JoinRoom_C2S{} }
func (m *JoinRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_C2S) ProtoMessage()    {}
func (*JoinRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *JoinRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_C2S.Unmarshal(m, b)
}
func (m *JoinRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_C2S.Marshal(b, m, deterministic)
}
func (m *JoinRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_C2S.Merge(m, src)
}
func (m *JoinRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_C2S.Size(m)
}
func (m *JoinRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_C2S proto.InternalMessageInfo

func (m *JoinRoom_C2S) GetCfg() string {
	if m != nil {
		return m.Cfg
	}
	return ""
}

type JoinRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoom_S2C) Reset()         { *m = JoinRoom_S2C{} }
func (m *JoinRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_S2C) ProtoMessage()    {}
func (*JoinRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *JoinRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_S2C.Unmarshal(m, b)
}
func (m *JoinRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_S2C.Marshal(b, m, deterministic)
}
func (m *JoinRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_S2C.Merge(m, src)
}
func (m *JoinRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_S2C.Size(m)
}
func (m *JoinRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_S2C proto.InternalMessageInfo

func (m *JoinRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type EnterRoom_S2C struct {
	RoomData             *RoomData     `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	IsChange             bool          `protobuf:"varint,2,opt,name=isChange,proto3" json:"isChange,omitempty"`
	Coordinates          []*Coordinate `protobuf:"bytes,3,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EnterRoom_S2C) Reset()         { *m = EnterRoom_S2C{} }
func (m *EnterRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*EnterRoom_S2C) ProtoMessage()    {}
func (*EnterRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *EnterRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoom_S2C.Unmarshal(m, b)
}
func (m *EnterRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoom_S2C.Marshal(b, m, deterministic)
}
func (m *EnterRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoom_S2C.Merge(m, src)
}
func (m *EnterRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_EnterRoom_S2C.Size(m)
}
func (m *EnterRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoom_S2C proto.InternalMessageInfo

func (m *EnterRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

func (m *EnterRoom_S2C) GetIsChange() bool {
	if m != nil {
		return m.IsChange
	}
	return false
}

func (m *EnterRoom_S2C) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type PlayerAction_C2S struct {
	DownBet              float64       `protobuf:"fixed64,1,opt,name=downBet,proto3" json:"downBet,omitempty"`
	Coordinates          []*Coordinate `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerAction_C2S) Reset()         { *m = PlayerAction_C2S{} }
func (m *PlayerAction_C2S) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_C2S) ProtoMessage()    {}
func (*PlayerAction_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *PlayerAction_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_C2S.Unmarshal(m, b)
}
func (m *PlayerAction_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_C2S.Marshal(b, m, deterministic)
}
func (m *PlayerAction_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_C2S.Merge(m, src)
}
func (m *PlayerAction_C2S) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_C2S.Size(m)
}
func (m *PlayerAction_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_C2S proto.InternalMessageInfo

func (m *PlayerAction_C2S) GetDownBet() float64 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_C2S) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type PlayerAction_S2C struct {
	LuckyBag             bool     `protobuf:"varint,1,opt,name=luckyBag,proto3" json:"luckyBag,omitempty"`
	Coin                 string   `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	CoinList             []string `protobuf:"bytes,3,rep,name=coinList,proto3" json:"coinList,omitempty"`
	StorageList          []string `protobuf:"bytes,4,rep,name=storageList,proto3" json:"storageList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction_S2C) Reset()         { *m = PlayerAction_S2C{} }
func (m *PlayerAction_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_S2C) ProtoMessage()    {}
func (*PlayerAction_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *PlayerAction_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_S2C.Unmarshal(m, b)
}
func (m *PlayerAction_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerAction_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_S2C.Merge(m, src)
}
func (m *PlayerAction_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_S2C.Size(m)
}
func (m *PlayerAction_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_S2C proto.InternalMessageInfo

func (m *PlayerAction_S2C) GetLuckyBag() bool {
	if m != nil {
		return m.LuckyBag
	}
	return false
}

func (m *PlayerAction_S2C) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *PlayerAction_S2C) GetCoinList() []string {
	if m != nil {
		return m.CoinList
	}
	return nil
}

func (m *PlayerAction_S2C) GetStorageList() []string {
	if m != nil {
		return m.StorageList
	}
	return nil
}

// 行动结算返回
type ActionResult_C2S struct {
	CoinList             []string      `protobuf:"bytes,1,rep,name=coinList,proto3" json:"coinList,omitempty"`
	Coordinates          []*Coordinate `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ActionResult_C2S) Reset()         { *m = ActionResult_C2S{} }
func (m *ActionResult_C2S) String() string { return proto.CompactTextString(m) }
func (*ActionResult_C2S) ProtoMessage()    {}
func (*ActionResult_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}

func (m *ActionResult_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResult_C2S.Unmarshal(m, b)
}
func (m *ActionResult_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResult_C2S.Marshal(b, m, deterministic)
}
func (m *ActionResult_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResult_C2S.Merge(m, src)
}
func (m *ActionResult_C2S) XXX_Size() int {
	return xxx_messageInfo_ActionResult_C2S.Size(m)
}
func (m *ActionResult_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResult_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResult_C2S proto.InternalMessageInfo

func (m *ActionResult_C2S) GetCoinList() []string {
	if m != nil {
		return m.CoinList
	}
	return nil
}

func (m *ActionResult_C2S) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type ActionResult_S2C struct {
	Account              float64  `protobuf:"fixed64,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionResult_S2C) Reset()         { *m = ActionResult_S2C{} }
func (m *ActionResult_S2C) String() string { return proto.CompactTextString(m) }
func (*ActionResult_S2C) ProtoMessage()    {}
func (*ActionResult_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}

func (m *ActionResult_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResult_S2C.Unmarshal(m, b)
}
func (m *ActionResult_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResult_S2C.Marshal(b, m, deterministic)
}
func (m *ActionResult_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResult_S2C.Merge(m, src)
}
func (m *ActionResult_S2C) XXX_Size() int {
	return xxx_messageInfo_ActionResult_S2C.Size(m)
}
func (m *ActionResult_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResult_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResult_S2C proto.InternalMessageInfo

func (m *ActionResult_S2C) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type ProgressBar_C2S struct {
	BetNum               int32    `protobuf:"varint,1,opt,name=betNum,proto3" json:"betNum,omitempty"`
	Coin                 string   `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProgressBar_C2S) Reset()         { *m = ProgressBar_C2S{} }
func (m *ProgressBar_C2S) String() string { return proto.CompactTextString(m) }
func (*ProgressBar_C2S) ProtoMessage()    {}
func (*ProgressBar_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{15}
}

func (m *ProgressBar_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProgressBar_C2S.Unmarshal(m, b)
}
func (m *ProgressBar_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProgressBar_C2S.Marshal(b, m, deterministic)
}
func (m *ProgressBar_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProgressBar_C2S.Merge(m, src)
}
func (m *ProgressBar_C2S) XXX_Size() int {
	return xxx_messageInfo_ProgressBar_C2S.Size(m)
}
func (m *ProgressBar_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_ProgressBar_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_ProgressBar_C2S proto.InternalMessageInfo

func (m *ProgressBar_C2S) GetBetNum() int32 {
	if m != nil {
		return m.BetNum
	}
	return 0
}

func (m *ProgressBar_C2S) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

type ProgressBar_S2C struct {
	ProBar               int32    `protobuf:"varint,1,opt,name=proBar,proto3" json:"proBar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProgressBar_S2C) Reset()         { *m = ProgressBar_S2C{} }
func (m *ProgressBar_S2C) String() string { return proto.CompactTextString(m) }
func (*ProgressBar_S2C) ProtoMessage()    {}
func (*ProgressBar_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{16}
}

func (m *ProgressBar_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProgressBar_S2C.Unmarshal(m, b)
}
func (m *ProgressBar_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProgressBar_S2C.Marshal(b, m, deterministic)
}
func (m *ProgressBar_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProgressBar_S2C.Merge(m, src)
}
func (m *ProgressBar_S2C) XXX_Size() int {
	return xxx_messageInfo_ProgressBar_S2C.Size(m)
}
func (m *ProgressBar_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ProgressBar_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ProgressBar_S2C proto.InternalMessageInfo

func (m *ProgressBar_S2C) GetProBar() int32 {
	if m != nil {
		return m.ProBar
	}
	return 0
}

type ThreePig struct {
	PigSuccess           float64  `protobuf:"fixed64,1,opt,name=PigSuccess,proto3" json:"PigSuccess,omitempty"`
	PigLoser_1           float64  `protobuf:"fixed64,2,opt,name=PigLoser_1,json=PigLoser1,proto3" json:"PigLoser_1,omitempty"`
	PigLoser_2           float64  `protobuf:"fixed64,3,opt,name=PigLoser_2,json=PigLoser2,proto3" json:"PigLoser_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreePig) Reset()         { *m = ThreePig{} }
func (m *ThreePig) String() string { return proto.CompactTextString(m) }
func (*ThreePig) ProtoMessage()    {}
func (*ThreePig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{17}
}

func (m *ThreePig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreePig.Unmarshal(m, b)
}
func (m *ThreePig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreePig.Marshal(b, m, deterministic)
}
func (m *ThreePig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreePig.Merge(m, src)
}
func (m *ThreePig) XXX_Size() int {
	return xxx_messageInfo_ThreePig.Size(m)
}
func (m *ThreePig) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreePig.DiscardUnknown(m)
}

var xxx_messageInfo_ThreePig proto.InternalMessageInfo

func (m *ThreePig) GetPigSuccess() float64 {
	if m != nil {
		return m.PigSuccess
	}
	return 0
}

func (m *ThreePig) GetPigLoser_1() float64 {
	if m != nil {
		return m.PigLoser_1
	}
	return 0
}

func (m *ThreePig) GetPigLoser_2() float64 {
	if m != nil {
		return m.PigLoser_2
	}
	return 0
}

// 获奖小游戏
type GetRewards_S2C struct {
	RewardsNum           int32     `protobuf:"varint,1,opt,name=rewardsNum,proto3" json:"rewardsNum,omitempty"`
	GetMoney             float64   `protobuf:"fixed64,2,opt,name=getMoney,proto3" json:"getMoney,omitempty"`
	LuckyPig             *ThreePig `protobuf:"bytes,3,opt,name=luckyPig,proto3" json:"luckyPig,omitempty"`
	Account              float64   `protobuf:"fixed64,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRewards_S2C) Reset()         { *m = GetRewards_S2C{} }
func (m *GetRewards_S2C) String() string { return proto.CompactTextString(m) }
func (*GetRewards_S2C) ProtoMessage()    {}
func (*GetRewards_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{18}
}

func (m *GetRewards_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRewards_S2C.Unmarshal(m, b)
}
func (m *GetRewards_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRewards_S2C.Marshal(b, m, deterministic)
}
func (m *GetRewards_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRewards_S2C.Merge(m, src)
}
func (m *GetRewards_S2C) XXX_Size() int {
	return xxx_messageInfo_GetRewards_S2C.Size(m)
}
func (m *GetRewards_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRewards_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_GetRewards_S2C proto.InternalMessageInfo

func (m *GetRewards_S2C) GetRewardsNum() int32 {
	if m != nil {
		return m.RewardsNum
	}
	return 0
}

func (m *GetRewards_S2C) GetGetMoney() float64 {
	if m != nil {
		return m.GetMoney
	}
	return 0
}

func (m *GetRewards_S2C) GetLuckyPig() *ThreePig {
	if m != nil {
		return m.LuckyPig
	}
	return nil
}

func (m *GetRewards_S2C) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

// 福袋掉落
type DownLuckyBag_S2C struct {
	LuckyBag1            int32    `protobuf:"varint,1,opt,name=luckyBag1,proto3" json:"luckyBag1,omitempty"`
	LuckyBag2            int32    `protobuf:"varint,2,opt,name=luckyBag2,proto3" json:"luckyBag2,omitempty"`
	CoinList             []string `protobuf:"bytes,3,rep,name=coinList,proto3" json:"coinList,omitempty"`
	Money                float64  `protobuf:"fixed64,4,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownLuckyBag_S2C) Reset()         { *m = DownLuckyBag_S2C{} }
func (m *DownLuckyBag_S2C) String() string { return proto.CompactTextString(m) }
func (*DownLuckyBag_S2C) ProtoMessage()    {}
func (*DownLuckyBag_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{19}
}

func (m *DownLuckyBag_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownLuckyBag_S2C.Unmarshal(m, b)
}
func (m *DownLuckyBag_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownLuckyBag_S2C.Marshal(b, m, deterministic)
}
func (m *DownLuckyBag_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownLuckyBag_S2C.Merge(m, src)
}
func (m *DownLuckyBag_S2C) XXX_Size() int {
	return xxx_messageInfo_DownLuckyBag_S2C.Size(m)
}
func (m *DownLuckyBag_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_DownLuckyBag_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_DownLuckyBag_S2C proto.InternalMessageInfo

func (m *DownLuckyBag_S2C) GetLuckyBag1() int32 {
	if m != nil {
		return m.LuckyBag1
	}
	return 0
}

func (m *DownLuckyBag_S2C) GetLuckyBag2() int32 {
	if m != nil {
		return m.LuckyBag2
	}
	return 0
}

func (m *DownLuckyBag_S2C) GetCoinList() []string {
	if m != nil {
		return m.CoinList
	}
	return nil
}

func (m *DownLuckyBag_S2C) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

// 重新生成金币
type ReCreatGold_S2C struct {
	CoinList             []string `protobuf:"bytes,1,rep,name=coinList,proto3" json:"coinList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReCreatGold_S2C) Reset()         { *m = ReCreatGold_S2C{} }
func (m *ReCreatGold_S2C) String() string { return proto.CompactTextString(m) }
func (*ReCreatGold_S2C) ProtoMessage()    {}
func (*ReCreatGold_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{20}
}

func (m *ReCreatGold_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReCreatGold_S2C.Unmarshal(m, b)
}
func (m *ReCreatGold_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReCreatGold_S2C.Marshal(b, m, deterministic)
}
func (m *ReCreatGold_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReCreatGold_S2C.Merge(m, src)
}
func (m *ReCreatGold_S2C) XXX_Size() int {
	return xxx_messageInfo_ReCreatGold_S2C.Size(m)
}
func (m *ReCreatGold_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ReCreatGold_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ReCreatGold_S2C proto.InternalMessageInfo

func (m *ReCreatGold_S2C) GetCoinList() []string {
	if m != nil {
		return m.CoinList
	}
	return nil
}

// 财神接金币
type PickUpGold_C2S struct {
	BetNum               int32    `protobuf:"varint,1,opt,name=betNum,proto3" json:"betNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PickUpGold_C2S) Reset()         { *m = PickUpGold_C2S{} }
func (m *PickUpGold_C2S) String() string { return proto.CompactTextString(m) }
func (*PickUpGold_C2S) ProtoMessage()    {}
func (*PickUpGold_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{21}
}

func (m *PickUpGold_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PickUpGold_C2S.Unmarshal(m, b)
}
func (m *PickUpGold_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PickUpGold_C2S.Marshal(b, m, deterministic)
}
func (m *PickUpGold_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PickUpGold_C2S.Merge(m, src)
}
func (m *PickUpGold_C2S) XXX_Size() int {
	return xxx_messageInfo_PickUpGold_C2S.Size(m)
}
func (m *PickUpGold_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PickUpGold_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PickUpGold_C2S proto.InternalMessageInfo

func (m *PickUpGold_C2S) GetBetNum() int32 {
	if m != nil {
		return m.BetNum
	}
	return 0
}

// 返回金额和倍数
type PickUpGold_S2C struct {
	Money                float64  `protobuf:"fixed64,1,opt,name=money,proto3" json:"money,omitempty"`
	Rate                 int32    `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Account              float64  `protobuf:"fixed64,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PickUpGold_S2C) Reset()         { *m = PickUpGold_S2C{} }
func (m *PickUpGold_S2C) String() string { return proto.CompactTextString(m) }
func (*PickUpGold_S2C) ProtoMessage()    {}
func (*PickUpGold_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{22}
}

func (m *PickUpGold_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PickUpGold_S2C.Unmarshal(m, b)
}
func (m *PickUpGold_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PickUpGold_S2C.Marshal(b, m, deterministic)
}
func (m *PickUpGold_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PickUpGold_S2C.Merge(m, src)
}
func (m *PickUpGold_S2C) XXX_Size() int {
	return xxx_messageInfo_PickUpGold_S2C.Size(m)
}
func (m *PickUpGold_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PickUpGold_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PickUpGold_S2C proto.InternalMessageInfo

func (m *PickUpGold_S2C) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *PickUpGold_S2C) GetRate() int32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *PickUpGold_S2C) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type Coordinate struct {
	Location             []string `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{23}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLocation() []string {
	if m != nil {
		return m.Location
	}
	return nil
}

// 修改房间区分配置
type ChangeRoomCfg_C2S struct {
	// 保存的config
	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// 二维数组
	Coordinates []*Coordinate `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	// 切换的config
	ChangeCfg            string   `protobuf:"bytes,3,opt,name=changeCfg,proto3" json:"changeCfg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRoomCfg_C2S) Reset()         { *m = ChangeRoomCfg_C2S{} }
func (m *ChangeRoomCfg_C2S) String() string { return proto.CompactTextString(m) }
func (*ChangeRoomCfg_C2S) ProtoMessage()    {}
func (*ChangeRoomCfg_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{24}
}

func (m *ChangeRoomCfg_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRoomCfg_C2S.Unmarshal(m, b)
}
func (m *ChangeRoomCfg_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRoomCfg_C2S.Marshal(b, m, deterministic)
}
func (m *ChangeRoomCfg_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRoomCfg_C2S.Merge(m, src)
}
func (m *ChangeRoomCfg_C2S) XXX_Size() int {
	return xxx_messageInfo_ChangeRoomCfg_C2S.Size(m)
}
func (m *ChangeRoomCfg_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRoomCfg_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRoomCfg_C2S proto.InternalMessageInfo

func (m *ChangeRoomCfg_C2S) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *ChangeRoomCfg_C2S) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *ChangeRoomCfg_C2S) GetChangeCfg() string {
	if m != nil {
		return m.ChangeCfg
	}
	return ""
}

// 返回配置信息
type ChangeRoomCfg_S2C struct {
	IsChange             bool          `protobuf:"varint,1,opt,name=isChange,proto3" json:"isChange,omitempty"`
	CoinList             []string      `protobuf:"bytes,2,rep,name=coinList,proto3" json:"coinList,omitempty"`
	Coordinates          []*Coordinate `protobuf:"bytes,3,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChangeRoomCfg_S2C) Reset()         { *m = ChangeRoomCfg_S2C{} }
func (m *ChangeRoomCfg_S2C) String() string { return proto.CompactTextString(m) }
func (*ChangeRoomCfg_S2C) ProtoMessage()    {}
func (*ChangeRoomCfg_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{25}
}

func (m *ChangeRoomCfg_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRoomCfg_S2C.Unmarshal(m, b)
}
func (m *ChangeRoomCfg_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRoomCfg_S2C.Marshal(b, m, deterministic)
}
func (m *ChangeRoomCfg_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRoomCfg_S2C.Merge(m, src)
}
func (m *ChangeRoomCfg_S2C) XXX_Size() int {
	return xxx_messageInfo_ChangeRoomCfg_S2C.Size(m)
}
func (m *ChangeRoomCfg_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRoomCfg_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRoomCfg_S2C proto.InternalMessageInfo

func (m *ChangeRoomCfg_S2C) GetIsChange() bool {
	if m != nil {
		return m.IsChange
	}
	return false
}

func (m *ChangeRoomCfg_S2C) GetCoinList() []string {
	if m != nil {
		return m.CoinList
	}
	return nil
}

func (m *ChangeRoomCfg_S2C) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type SendCoordinate_C2S struct {
	Coordinates          []*Coordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendCoordinate_C2S) Reset()         { *m = SendCoordinate_C2S{} }
func (m *SendCoordinate_C2S) String() string { return proto.CompactTextString(m) }
func (*SendCoordinate_C2S) ProtoMessage()    {}
func (*SendCoordinate_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{26}
}

func (m *SendCoordinate_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCoordinate_C2S.Unmarshal(m, b)
}
func (m *SendCoordinate_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCoordinate_C2S.Marshal(b, m, deterministic)
}
func (m *SendCoordinate_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCoordinate_C2S.Merge(m, src)
}
func (m *SendCoordinate_C2S) XXX_Size() int {
	return xxx_messageInfo_SendCoordinate_C2S.Size(m)
}
func (m *SendCoordinate_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCoordinate_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_SendCoordinate_C2S proto.InternalMessageInfo

func (m *SendCoordinate_C2S) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type ErrorMsg_S2C struct {
	MsgData              string   `protobuf:"bytes,1,opt,name=msgData,proto3" json:"msgData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMsg_S2C) Reset()         { *m = ErrorMsg_S2C{} }
func (m *ErrorMsg_S2C) String() string { return proto.CompactTextString(m) }
func (*ErrorMsg_S2C) ProtoMessage()    {}
func (*ErrorMsg_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{27}
}

func (m *ErrorMsg_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMsg_S2C.Unmarshal(m, b)
}
func (m *ErrorMsg_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMsg_S2C.Marshal(b, m, deterministic)
}
func (m *ErrorMsg_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMsg_S2C.Merge(m, src)
}
func (m *ErrorMsg_S2C) XXX_Size() int {
	return xxx_messageInfo_ErrorMsg_S2C.Size(m)
}
func (m *ErrorMsg_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMsg_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMsg_S2C proto.InternalMessageInfo

func (m *ErrorMsg_S2C) GetMsgData() string {
	if m != nil {
		return m.MsgData
	}
	return ""
}

func init() {
	proto.RegisterEnum("msg.MessageID", MessageID_name, MessageID_value)
	proto.RegisterType((*Ping)(nil), "msg.Ping")
	proto.RegisterType((*Pong)(nil), "msg.Pong")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*Login_C2S)(nil), "msg.Login_C2S")
	proto.RegisterType((*Login_S2C)(nil), "msg.Login_S2C")
	proto.RegisterType((*Logout_C2S)(nil), "msg.Logout_C2S")
	proto.RegisterType((*Logout_S2C)(nil), "msg.Logout_S2C")
	proto.RegisterType((*RoomData)(nil), "msg.RoomData")
	proto.RegisterType((*JoinRoom_C2S)(nil), "msg.JoinRoom_C2S")
	proto.RegisterType((*JoinRoom_S2C)(nil), "msg.JoinRoom_S2C")
	proto.RegisterType((*EnterRoom_S2C)(nil), "msg.EnterRoom_S2C")
	proto.RegisterType((*PlayerAction_C2S)(nil), "msg.PlayerAction_C2S")
	proto.RegisterType((*PlayerAction_S2C)(nil), "msg.PlayerAction_S2C")
	proto.RegisterType((*ActionResult_C2S)(nil), "msg.ActionResult_C2S")
	proto.RegisterType((*ActionResult_S2C)(nil), "msg.ActionResult_S2C")
	proto.RegisterType((*ProgressBar_C2S)(nil), "msg.ProgressBar_C2S")
	proto.RegisterType((*ProgressBar_S2C)(nil), "msg.ProgressBar_S2C")
	proto.RegisterType((*ThreePig)(nil), "msg.ThreePig")
	proto.RegisterType((*GetRewards_S2C)(nil), "msg.GetRewards_S2C")
	proto.RegisterType((*DownLuckyBag_S2C)(nil), "msg.DownLuckyBag_S2C")
	proto.RegisterType((*ReCreatGold_S2C)(nil), "msg.ReCreatGold_S2C")
	proto.RegisterType((*PickUpGold_C2S)(nil), "msg.PickUpGold_C2S")
	proto.RegisterType((*PickUpGold_S2C)(nil), "msg.PickUpGold_S2C")
	proto.RegisterType((*Coordinate)(nil), "msg.coordinate")
	proto.RegisterType((*ChangeRoomCfg_C2S)(nil), "msg.ChangeRoomCfg_C2S")
	proto.RegisterType((*ChangeRoomCfg_S2C)(nil), "msg.ChangeRoomCfg_S2C")
	proto.RegisterType((*SendCoordinate_C2S)(nil), "msg.SendCoordinate_C2S")
	proto.RegisterType((*ErrorMsg_S2C)(nil), "msg.ErrorMsg_S2C")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 1014 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0xae, 0x2c, 0x27, 0xb1, 0x27, 0x7f, 0x0c, 0xd7, 0xf1, 0xba, 0x41, 0xbb, 0x30, 0x78, 0x28,
	0xbc, 0x45, 0xbb, 0x45, 0xd4, 0x53, 0x0f, 0x3d, 0xd4, 0xca, 0x22, 0x70, 0x61, 0x2f, 0x0c, 0xd9,
	0x45, 0x8f, 0x01, 0x57, 0xa6, 0x19, 0xc1, 0x96, 0x18, 0x90, 0x72, 0x83, 0x00, 0x45, 0xd1, 0x4b,
	0x0f, 0x3d, 0xf6, 0x61, 0xfa, 0x7e, 0x05, 0x29, 0x51, 0x96, 0x14, 0x37, 0x1b, 0xe4, 0xa6, 0x6f,
	0x66, 0x38, 0xf3, 0xcd, 0x70, 0x66, 0x28, 0x68, 0xc7, 0x8a, 0xbf, 0xbb, 0x93, 0x22, 0x15, 0xd8,
	0x8d, 0x15, 0x27, 0xfb, 0xd0, 0x9c, 0x46, 0x09, 0x27, 0x5f, 0x41, 0x73, 0x2a, 0x12, 0x8e, 0xdf,
	0x00, 0x28, 0x26, 0x7f, 0x63, 0x72, 0x1e, 0xc5, 0xac, 0xe7, 0xf4, 0x9d, 0x81, 0x1b, 0x94, 0x24,
	0x64, 0x0d, 0x30, 0x5d, 0xd3, 0x07, 0x26, 0x47, 0xc9, 0x52, 0xe0, 0x13, 0x68, 0x8c, 0x16, 0xc6,
	0xaa, 0x1d, 0x34, 0x46, 0x0b, 0x7c, 0x01, 0xad, 0x24, 0x0a, 0x57, 0x1f, 0x68, 0xcc, 0x7a, 0x0d,
	0x23, 0x2d, 0x30, 0xee, 0xc1, 0xc1, 0x2d, 0xa3, 0x8b, 0x51, 0xcc, 0x7b, 0xae, 0x51, 0x59, 0xa8,
	0x35, 0x34, 0x0c, 0xc5, 0x26, 0x49, 0x7b, 0xcd, 0xbe, 0x33, 0x70, 0x02, 0x0b, 0xc9, 0x04, 0xda,
	0x63, 0xc1, 0xa3, 0xe4, 0xc6, 0xf7, 0x66, 0xbb, 0x82, 0x4d, 0xa9, 0x52, 0xbf, 0x0a, 0xb9, 0xb0,
	0xc1, 0x2c, 0xc6, 0x1d, 0xd8, 0x9b, 0x8b, 0x15, 0x4b, 0xf2, 0x50, 0x19, 0x20, 0x73, 0xeb, 0x6e,
	0xe6, 0xf9, 0xb8, 0x0b, 0xfb, 0x23, 0x35, 0xa4, 0xe1, 0xca, 0xb8, 0x6c, 0x05, 0x39, 0xc2, 0xdf,
	0x01, 0xdc, 0x15, 0x19, 0x1a, 0xc7, 0x87, 0xde, 0xe9, 0x3b, 0x5d, 0xb6, 0x6d, 0xe2, 0x41, 0xc9,
	0x84, 0x1c, 0x01, 0x8c, 0x05, 0x17, 0x9b, 0x54, 0xb3, 0x2c, 0xa1, 0x99, 0xe7, 0x93, 0xbf, 0x1c,
	0x68, 0x05, 0x42, 0xc4, 0x57, 0x34, 0xa5, 0x3a, 0xa2, 0x14, 0x22, 0x2e, 0x92, 0xc8, 0x91, 0x26,
	0x1b, 0x2e, 0xf9, 0xc8, 0x66, 0x91, 0x81, 0x1a, 0x0f, 0xf7, 0x93, 0x3c, 0x74, 0x3d, 0x42, 0x11,
	0x25, 0xe3, 0x48, 0xe9, 0x3a, 0xba, 0xba, 0x1e, 0x16, 0x93, 0x3e, 0x1c, 0xfd, 0x2c, 0xa2, 0x44,
	0x53, 0x31, 0xb5, 0x44, 0xe0, 0x86, 0x4b, 0x9e, 0xf3, 0xd0, 0x9f, 0xe4, 0x87, 0x92, 0x85, 0x2e,
	0xcf, 0x5b, 0x68, 0xc9, 0x9c, 0xb8, 0x31, 0x3b, 0xf4, 0x8e, 0x4d, 0x70, 0x9b, 0x4d, 0x50, 0xa8,
	0xc9, 0xdf, 0x0e, 0x1c, 0xbf, 0x4f, 0x52, 0x26, 0x5f, 0x70, 0x58, 0xb3, 0x8e, 0x94, 0x7f, 0x4b,
	0x13, 0x9e, 0xb5, 0x4c, 0x2b, 0x28, 0x30, 0xbe, 0x84, 0xc3, 0x50, 0x08, 0xb9, 0x88, 0x12, 0x9a,
	0x32, 0xd5, 0x73, 0xfb, 0x6e, 0x51, 0x83, 0xad, 0x3c, 0x28, 0xdb, 0x90, 0x1b, 0x40, 0x59, 0x79,
	0x7e, 0x0a, 0xd3, 0x48, 0x64, 0x8d, 0xd3, 0x83, 0x83, 0x85, 0xb8, 0x4f, 0x86, 0x2c, 0x35, 0x64,
	0x9c, 0xc0, 0xc2, 0x7a, 0x80, 0xc6, 0x33, 0x02, 0xfc, 0xe9, 0xd4, 0x22, 0xe8, 0x7c, 0x2f, 0xa0,
	0xb5, 0xde, 0x84, 0xab, 0x87, 0x21, 0xe5, 0x79, 0x37, 0x15, 0x18, 0x63, 0x68, 0xea, 0x6b, 0xc8,
	0x2f, 0xd7, 0x7c, 0x57, 0xae, 0xca, 0xad, 0x5e, 0x15, 0xee, 0xc3, 0xa1, 0x4a, 0x85, 0xa4, 0x9c,
	0x95, 0x6e, 0xb2, 0x2c, 0x22, 0x14, 0x50, 0x16, 0x3b, 0x60, 0x6a, 0xb3, 0x36, 0x6d, 0x57, 0xf1,
	0xe8, 0xd4, 0x3c, 0xbe, 0x20, 0xcb, 0x6f, 0x6a, 0x21, 0x74, 0x92, 0xa5, 0x31, 0x75, 0xaa, 0x63,
	0xfa, 0x23, 0x9c, 0x4e, 0xa5, 0xe0, 0x92, 0x29, 0x35, 0xa4, 0xd2, 0xf0, 0xe9, 0xc2, 0xfe, 0x47,
	0x96, 0x7e, 0xd8, 0xc4, 0xc6, 0x76, 0x2f, 0xc8, 0xd1, 0xae, 0x6a, 0x90, 0xb7, 0xd5, 0xe3, 0xf9,
	0x70, 0xde, 0x49, 0x31, 0xa4, 0xd2, 0x1e, 0xcf, 0x10, 0xb9, 0x85, 0xd6, 0xfc, 0x56, 0x32, 0x36,
	0x8d, 0xcc, 0xaa, 0x9a, 0x46, 0x7c, 0xb6, 0x09, 0x43, 0xa6, 0x54, 0x4e, 0xa9, 0x24, 0xc1, 0x5f,
	0x1a, 0xfd, 0x58, 0x28, 0x26, 0x6f, 0x2e, 0x4d, 0x40, 0x27, 0x68, 0x5b, 0xc9, 0x65, 0x45, 0xed,
	0x99, 0xf9, 0x2a, 0xa9, 0x3d, 0xf2, 0x8f, 0x03, 0x27, 0xd7, 0x2c, 0x0d, 0xd8, 0x3d, 0x95, 0x0b,
	0x65, 0x48, 0xbd, 0x01, 0x90, 0x19, 0xdc, 0xe6, 0x55, 0x92, 0xe8, 0x3b, 0xe0, 0x2c, 0x9d, 0x88,
	0x84, 0x3d, 0xe4, 0xe1, 0x0a, 0xac, 0x27, 0xc2, 0x74, 0xc4, 0x34, 0xe2, 0xf9, 0x2c, 0x67, 0x13,
	0x61, 0xb3, 0x09, 0x0a, 0xf5, 0x13, 0xeb, 0x50, 0xf7, 0xde, 0x95, 0xb8, 0x4f, 0xc6, 0x79, 0x6f,
	0x19, 0x56, 0x5f, 0x40, 0xdb, 0xf6, 0xda, 0x65, 0x4e, 0x6a, 0x2b, 0x28, 0x6b, 0x3d, 0x43, 0xaa,
	0xa4, 0xf5, 0x9e, 0xec, 0xc3, 0x0e, 0xec, 0xc5, 0x26, 0x95, 0x8c, 0x44, 0x06, 0xc8, 0xb7, 0x70,
	0x1a, 0x30, 0x5f, 0x32, 0x9a, 0x5e, 0x8b, 0xf5, 0xc2, 0x36, 0xff, 0xff, 0xb5, 0x1e, 0x19, 0xc0,
	0xc9, 0x34, 0x0a, 0x57, 0xbf, 0xdc, 0x19, 0xeb, 0x27, 0x1a, 0x83, 0xcc, 0x2b, 0x96, 0xda, 0x6f,
	0x41, 0xc0, 0x29, 0x11, 0xd0, 0x0d, 0x24, 0x69, 0xca, 0xf2, 0x5c, 0xcc, 0x77, 0xb9, 0x62, 0x6e,
	0xb5, 0x62, 0x03, 0x80, 0x6d, 0x5b, 0x9b, 0x31, 0x15, 0x21, 0xd5, 0x7d, 0x6d, 0x99, 0x5a, 0x4c,
	0x7e, 0x87, 0xb3, 0x6c, 0xeb, 0xe8, 0x1d, 0xe5, 0x2f, 0xb9, 0x25, 0x1b, 0x8a, 0x64, 0x19, 0xd9,
	0x4d, 0x99, 0xa3, 0x17, 0x4c, 0x94, 0xbe, 0x88, 0xd0, 0xf8, 0xf7, 0x97, 0xf6, 0x01, 0xdc, 0x0a,
	0xc8, 0x1f, 0xf5, 0xe8, 0x79, 0x61, 0x8b, 0xd5, 0xe8, 0xd4, 0x56, 0x63, 0xb9, 0xe8, 0x8d, 0xa7,
	0xe7, 0xfd, 0x39, 0x6b, 0xf3, 0x1a, 0xf0, 0x8c, 0x25, 0x0b, 0xbf, 0x10, 0x99, 0xf4, 0x6b, 0x8e,
	0x9c, 0x67, 0x38, 0x1a, 0xc0, 0xd1, 0x7b, 0x29, 0x85, 0x9c, 0x28, 0x6e, 0x97, 0x46, 0xac, 0x78,
	0xf1, 0x10, 0xb4, 0x03, 0x0b, 0xbf, 0xfe, 0xb7, 0x09, 0xed, 0x09, 0x53, 0x8a, 0x72, 0x36, 0xba,
	0xc2, 0x47, 0xd0, 0x9a, 0xcc, 0xae, 0x6f, 0xf4, 0xbf, 0x08, 0xfa, 0xac, 0x40, 0x22, 0xe1, 0xc8,
	0xc1, 0x67, 0x70, 0xac, 0x51, 0xf1, 0x27, 0x80, 0x1a, 0x55, 0xd1, 0xcc, 0xf3, 0x91, 0x8b, 0x31,
	0x9c, 0xe4, 0xa2, 0xfc, 0x29, 0x46, 0xcd, 0x9a, 0x4c, 0xdb, 0xed, 0xe1, 0x0e, 0x20, 0x2d, 0x2b,
	0x3f, 0x87, 0x68, 0xff, 0x91, 0x54, 0xdb, 0x1e, 0xe0, 0x73, 0x38, 0xd3, 0xd2, 0xca, 0xe3, 0x86,
	0x5a, 0xb8, 0x07, 0x1d, 0x43, 0xaf, 0xf6, 0xd0, 0xa0, 0xf6, 0x4e, 0xcd, 0xcc, 0xf7, 0x10, 0x58,
	0x4d, 0x7d, 0x71, 0xa3, 0xc3, 0x9d, 0x1a, 0x1d, 0xe7, 0x08, 0xbf, 0x86, 0x57, 0xc6, 0x5b, 0x75,
	0xb7, 0xa2, 0xe3, 0x5d, 0x0a, 0x7d, 0xe2, 0xc4, 0xfa, 0xaa, 0x2f, 0x09, 0x74, 0x6a, 0x8f, 0xd4,
	0x86, 0x17, 0x21, 0xdc, 0x05, 0xac, 0x15, 0xd5, 0x5d, 0x87, 0xce, 0xac, 0xbc, 0x3a, 0xbe, 0x08,
	0xef, 0x90, 0x6b, 0xfb, 0x57, 0xf8, 0x73, 0x38, 0xd7, 0xf2, 0x47, 0x43, 0x84, 0x3a, 0xbb, 0x55,
	0xfa, 0xd4, 0x39, 0xbe, 0x80, 0xae, 0x56, 0x3d, 0x6e, 0x3e, 0xd4, 0xb5, 0x77, 0x52, 0xee, 0x27,
	0xf4, 0xfa, 0xe3, 0xbe, 0xf9, 0x7b, 0xfd, 0xfe, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x88,
	0xae, 0x32, 0xca, 0x0a, 0x00, 0x00,
}
